name: Auto-Train
run-name: Auto-train the models based on the new commit by ${{ github.actor }}.
on: [push]
jobs: 
  AutoTrain:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Auto-train triggered by ${{ github.event_name }}"
      - run: echo "Runner OS is ${{ runner.os }}; Branch is ${{ github.ref }}; Repository is ${{ github.repository }}"
      - name: Check out code
        uses: actions/checkout@v4
      - run: echo "Repo ${{ github.repository }} cloned. "
      - name: Environment setup
        run: |
          echo "Installing Icarus Verilog (required by PyVerilog)"
          sudo apt install iverilog -y
          echo "Installing Python requirements"
          pip install -r requirements.txt
      - name: Training
        run: python train.py
      - name: Upload trained model (good.keras)
        uses: actions/upload-artifact@v3
        with:
          name: good.keras
          path: models/good.keras
      - name: Upload trained model (hasfsm.keras)
        uses: actions/upload-artifact@v3
        with:
          name: hasfsm.keras
          path: models/hasfsm.keras
      - name: Upload trained model (labeled.keras)
        uses: actions/upload-artifact@v3
        with:
          name: labeled.keras
          path: models/labeled.keras
      - name: Upload trained model (sensitivity.keras)
        uses: actions/upload-artifact@v3
        with:
          name: sensitivity.keras
          path: models/sensitivity.keras
      - name: Upload trained model (transitions.keras)
        uses: actions/upload-artifact@v3
        with:
          name: transitions.keras
          path: models/transitions.keras
      - run: echo "Job status is ${{ job.status }}"
      - name: Training log
        run: cat action.log
